{% set name = "optuna" %}
{% set version = "4.6.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 89e38c2447c7f793a726617b8043f01e31f0bad54855040db17eb3b49404a369

build:
  number: 0
  entry_points:
    - optuna = optuna.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - alembic >=1.5.0
    - colorlog
    - numpy
    - packaging >=20.0
    - python >={{ python_min }}
    - sqlalchemy >=1.3.0
    - tqdm
    - PyYAML

test:
  imports:
    - optuna
  commands:
    - optuna --help

about:
  home: https://optuna.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A hyperparameter optimization framework
  doc_url: https://optuna.readthedocs.io/
  dev_url: https://github.com/optuna/optuna

extra:
  recipe-maintainers:
    - eukaryo
    - y0z
    - nabenabe0928
    - c-bata
    - contramundum53
    - g-votte
    - himkt
    - HideakiImamura
    - hvy
    - iwiwi
    - knshnb
    - not522
    - sile
    - smly
    - toshihikoyanase
    - ytsmiling
