{% set name = "optuna" %}
{% set version = "2.0.0rc0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e71ff691a4d932f2f43b8c4670d834a541045c99550adaa61c40979c46ee8710

build:
  number: 0
  entry_points:
    - optuna = optuna.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - alembic
    - cliff
    - cmaes
    - colorlog
    - joblib
    - numpy
    - python >=3.5
    - scipy
    - sqlalchemy >=1.1.0
    - tqdm

test:
  imports:
    - optuna
    - optuna.integration
    - optuna.pruners
    - optuna.samplers
    - optuna.samplers.tpe
    - optuna.storages
    - optuna.storages.rdb
    - optuna.testing
    - tests
    - tests.integration_tests
    - tests.pruners_tests
    - tests.samplers_tests
    - tests.storages_tests
    - tests.storages_tests.rdb_tests
  commands:
    - optuna --help
  source_files:
    - tests

about:
  home: https://optuna.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A hyperparameter optimization framework
  doc_url: https://optuna.readthedocs.io/
  dev_url: https://github.com/optuna/optuna

extra:
  recipe-maintainers:
    - g-votte
    - HideakiImamura
    - hvy
    - iwiwi
    - sile
    - smly
    - toshihikoyanase
    - ytsmiling
