travis:
  secure:
    BINSTAR_TOKEN: nig8Dl1Nf+9skxsxeGgt0kz0ZEaJsqGjkpphU/YyZ65VU00OzpSbzPYxpREzSqnNMCiNzU1HrlB/MkxG3Hcncvzu73JQegRZsXtVQzUoRGhFrTfH8W6swQzFNOSm4/nZlVOMFfCV1Q5VqhG2+xZhl4yYcJFUNatOzllTd8Q2ORQvvieiQqT4W2g7xNAVwZWDB2CpGDZa5/b/Rz4k9dOnAgawaqlWQvpQkpZ1F9UEhL3aUWRiP7jI12i4uwcpD+kvVRBS+wHglsgm7pywtzYXFoy6+IGyznVZO5SIVP3DoNK53NxawkYTU30E4/wEbGgiskXo5SEbnaskLH1omsSqASMNABZNaedwhrh+nsgWG3kmlzYNqhD/9fT3YrzBT1y5uDzZhV5ibDOoQ8S8qa7RiZl8qhj+msF5AlfSBHfMvD8oidhXOaMwqwPM7tmJVhv9FdRrTY90Sb9h2K7jq/1xipxXr/6t7aZY/qbZ9Wc75N9IKjzKUQYBW8jW1PMB+HjK8Ga2JSsJgSYdBoKY0m28ngoPh7VeT4zwyX2e6kHy1dd7Zu3JNeqgrnMEQEPmkdqDAS+TJc7oyjKS067FN5SJ28ICQtEIeDtcoSsYYtqZDWJQV3mINv9dsAB3Acs/MJnmm9P/PY/ExHR38oN/HFXxeTuAHAB7SHgHmWKi+wf94rg=
conda_forge_output_validation: true
channels:
  targets:
    - ["conda-forge", "rc"]
